version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./:/python-docker
        
    frontend:
        build:
            context: ./front_config
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/python-docker